name: Node.js CI

on:
  push:
    branches: [ "host" ]
    

jobs:
  build:
    runs-on: self-hoste

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Stop Systemctl module "Elio-test-app"
      run: sudo systemctl stop Elio-test-app

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start Systemctl module "Elio-test-app"
      run: sudo systemctl start Elio-test-app

    - name: Complete task
      run: echo "Task completed successfully."
